# Generated by Django 3.2.21 on 2023-10-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20231025_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=1, max_length=200, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
